http: 
 # serversTransports:
 #   foobar:
 #     serverName: internalServiceCertificateSubject 
  routers:
    tnsv01:
      entryPoints:
        - "https"
      rule: "Host(`tnsv01.qtslabs.com`)"
      middlewares:
        - chain-authelia@file
      tls:
        - "true"
      service: tnsv01
  services:
    tnsv01:
      loadBalancer:
        servers:
          - url: "http://172.20.11.87:80"
        passHostHeader: true